### ISSUE TITLE
ZipSigner fixes

### ISSUE THREAD

**Issue by HemanthJabalpuri** [micro5k/microg-unofficial-installer#20] opened 2020-12-24 12:16 UTC
@ale5000-git
I saw below issues in Magisk by you.
https://github.com/topjohnwu/Magisk/issues/828
https://github.com/topjohnwu/Magisk/issues/932
https://github.com/topjohnwu/Magisk/issues/954
Now zipsigner does not support flashable zip signing.

For fixing these issues, we can simply use my mod at https://forum.xda-developers.com/t/app-android-no-pc-sign-apk-zip-within-android.3835975/post-81324327

How it fixes these issues is, it will not re-compress at all. It will just add footer to the zip file. So it will not do any manipulations to the zip entries.

I am also wanted to update ZipSigner, but it removed flashable zip signing support. See https://github.com/topjohnwu/Magisk/issues/3598

Thanks

**Comment by ale5000-git** [comment] 2022-05-23 12:56
Thanks for the works but currently I don't want to change since it will probably affect build reproducibility (you can build it on both Linux and Windows and it will produce the same bit-exact zip file).

About the issue with special chars it was only a bug report I don't really need them, about the other 2 issues I have already work-arounded them.
I'm closing it for now although I may reconsider it in the future.

**Closed by ale5000-git** 2022-05-23 12:56 UTC
