### ISSUE TITLE
Magisk Rooted Android 12 Stock - Can't install by manual script or flash zip from recovery

### ISSUE THREAD

**Issue by ethanhall** [micro5k/microg-unofficial-installer#34] opened 2022-06-29 19:47 UTC
Hello,

I have mounted RW and tried to run the install script from both local terminal and ADB Shell on Windows.  Launched from either internal or external storage,I get the results below.

I have been searching XDA and SO with no solution so far.  I'm sure I am doing something bone-headed, any ideas?

d2s:/ $ su
d2s:/ #
d2s:/ # mount -o rw,remount /
d2s:/ #
d2s:/ # cd /storage/2C41-653F/Repo/micro5k
d2s:/storage/2C41-653F/Repo/micro5k # sh install.sh
install.sh[38]: .: /inc/common.sh: No such file or directory

Or:

d2s:/storage/2C41-653F/Repo/micro5k # sh ./install.sh
install.sh[38]: .: /inc/common.sh: No such file or directory

Or:

d2s:/storage/2C41-653F/Repo/micro5k # su -c sh ./install.sh
install.sh[38]: .: /inc/common.sh: No such file or directory

With ADB sideload or apply update from SD, I get:

E: Signature verification failed
E: error: 21
<...>
Installation aborted.

Flashing the zip with terminal from SD fails:

![Screenshot2](https://user-images.githubusercontent.com/802448/176552269-07328eb1-b9f8-46a1-9614-7787ed1b1ead.jpg)

**Comment by ale5000-git** [comment] 2022-06-30 11:21
1) About flashing from terminal, I didn't know there was an option to flash from terminal, what app allow it?
The zip isn't tested in this condition so I don't know.
Something seems wrong, does /system/priv-app and /system/framework/framework-res.apk exist?

2) The zip is supposed to work only from recovery (or ADB sideload) or from FlashFire (not from terminal).
The only exception is uninstall.sh that has additional uses.

The TWRP recovery (and many custom recoveries) have an option to disable signature verification, what recovery do you have?
On old phones enabling "Android debugging" inside "Developer options" before reboot in the recovery may make it accept the test signing keys but on new phones problat not.

**Comment by ale5000-git** [comment] 2022-07-01 12:40
@ethanhall
Could you please try the zip from here: https://github.com/micro5k/microg-unofficial-installer/actions/runs/2596641867
that should have better support for running from terminal?

PS: It is a zip inside a zip, you shouls use the inner zip.

**Comment by ale5000-git** [comment] 2022-12-05 11:06
@ethanhall
Are you still here?

**Comment by ale5000-git** [comment] 2022-12-21 17:11
The user is disappeared by I believe the issue is already fixed in the latest code here and in the version v1.2.0-beta (not yet released).

**Closed by ale5000-git** 2022-12-21 17:11 UTC
